apiVersion: v1
kind: Service
metadata:
  name: managed-identity-wallets-local-lb
spec:
  # loadBalancerIP: 20.113.25.108
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: managed-identity-wallets